### PR TITLE
CocoaPods TestJam! Adding some tests and CI support

### PR DESCRIPTION
**Pull request by yas375**
Hi @hons82! I'm taking part in [TestJam](http://blog.cocoapods.org/Prepare-to-Jam/) and have decided to spend some time on your project :)

I've added some basic tests for the library. Added Travis CI and Coverall.io support. You would need to turn on them on yourself as I don't have admin rights to your repo.

https://coveralls.io/
https://travis-ci.org

### CODE REVIEW

**Comment by yas375** [comment]
I'm double-checking that Travis CI and Coverall integrations work. Stay tuned

**Comment by yas375** [comment]
Ready for review.

https://travis-ci.org/yas375/THSegmentedPager
https://coveralls.io/r/yas375/THSegmentedPager

**Comment by hons82** [comment]
Hi,

thanks a lot. I hope I activated everything now

~Hannes

**Comment by yas375** [comment]
I've force pushed the branch to trigger TravisCI build. From what I can see you've configured integrations right :+1: 

https://travis-ci.org/hons82/THSegmentedPager/builds/59286117
https://coveralls.io/builds/2380293

Would be nice to get it merged ;)

**Comment by hons82** [comment]
Hi,
I'm currently trying to "copy" what you did to another repo.
[THCache](https://github.com/hons82/THCache) but I can't get coveralls to work properly...

Could you help me with that?

THX

**Pull request merged**
